variable "rg_name" {}
variable "sn_be_cidr" {}
variable "sn_fe_cidr" {}
variable "sn_fe_name" {}
variable "sn_be_name" {}
variable "vn_cidr" {}
variable "vn_name" {}
variable "location" {}
variable "vm_size" {}
variable "vm_name" {}  
variable "vm_interface_name" {}
variable "sg_name" {}